### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by FriskyJacket** [CCCNJ-CS216/Five-Points#6]
Lots of changes cant figure out how to open in net beans now.

**Comment by natepisarski** [comment]
It should open right up. The only change that might impact opening it up in Netbeans is I moved some stuff around so it's easier for the teams to focus on what they need (i.e, the graphics are in a separate package from the actual sim elements, Pair and Queue and stuff are off in their own little world). 

...

that said, I can't get it to open either. The project literally crashes netbeans when I open it. Time to investigate.

**Comment by sweissman** [comment]
This is what a Netbeans project root directory looks like:

[image: Inline image 1]

...and this is what unzipped dir looks like now. (.idea folder doesn't look
like a Netbeans build):

[image: Inline image 2]
On Sat, Nov 21, 2015 at 8:48 PM, Nate Pisarski notifications@github.com
wrote:

> It should open right up. The only change that might impact opening it up
> in Netbeans is I moved some stuff around so it's easier for the teams to
> focus on what they need (i.e, the graphics are in a separate package from
> the actual sim elements, Pair and Queue and stuff are off in their own
> little world).
> 
> ...
> 
> that said, I can't get it to open either. The project literally crashes
> netbeans when I open it. Time to investigate.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CCCNJ-CS216/Five-Points/issues/6#issuecomment-158699327
> .

## 

Stephen B. Weissman, M.A.T.(English), MS Comp Sci
Asst Professor Computer Science

**Comment by sweissman** [comment]
OK.  Here's what I did. (Hope I didn't leave out anything):
1. Created _new_ NetBeans Project:
     Selected "Java FX with Existing Sources"
2. In the window where you put existing source package folders, I browsed
   to select the src folder from the Five Points Master.
   
   Everything loaded into separated source packages in the NetBeans
   project navigator...  and I was able to compile and run: I assume I got
   everything!

On Sat, Nov 21, 2015 at 9:55 PM, Steve Weissman sweissman@cccnj.edu wrote:

> This is what a Netbeans project root directory looks like:
> 
> [image: Inline image 1]
> 
> ...and this is what unzipped dir looks like now. (.idea folder doesn't
> look like a Netbeans build):
> 
> [image: Inline image 2]
> On Sat, Nov 21, 2015 at 8:48 PM, Nate Pisarski notifications@github.com
> wrote:
> 
> > It should open right up. The only change that might impact opening it up
> > in Netbeans is I moved some stuff around so it's easier for the teams to
> > focus on what they need (i.e, the graphics are in a separate package from
> > the actual sim elements, Pair and Queue and stuff are off in their own
> > little world).
> > 
> > ...
> > 
> > that said, I can't get it to open either. The project literally crashes
> > netbeans when I open it. Time to investigate.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/CCCNJ-CS216/Five-Points/issues/6#issuecomment-158699327
> > .
> 
> ## 
> 
> Stephen B. Weissman, M.A.T.(English), MS Comp Sci
> Asst Professor Computer Science

## 

Stephen B. Weissman, M.A.T.(English), MS Comp Sci
Asst Professor Computer Science

**Comment by natepisarski** [comment]
Hey @sweissman, can you put the modified netbeans project file (the manifest and the build.xml) into the project root? Thanks.

Or if not, email me the zip of that stuff.

**Comment by sweissman** [comment]
I am _not_ a "pusher"!! ... but I attach the zip of the Netbeans project
from yesterday's download.  (I had to rename from .zip to .zpp to finesse
the gmaiol attachment police).

On Sun, Nov 22, 2015 at 10:49 AM, Nate Pisarski notifications@github.com
wrote:

> Hey @sweissman https://github.com/sweissman, can you put the modified
> netbeans project file (the manifest and the build.xml) into the project
> root? Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CCCNJ-CS216/Five-Points/issues/6#issuecomment-158770421
> .

## 

Stephen B. Weissman, M.A.T.(English), MS Comp Sci
Asst Professor Computer Science

**Comment by sweissman** [comment]
Sorry--  Ignore last.   CORRECT zip file attached

On Sun, Nov 22, 2015 at 10:49 AM, Nate Pisarski notifications@github.com
wrote:

> Hey @sweissman https://github.com/sweissman, can you put the modified
> netbeans project file (the manifest and the build.xml) into the project
> root? Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CCCNJ-CS216/Five-Points/issues/6#issuecomment-158770421
> .

## 

Stephen B. Weissman, M.A.T.(English), MS Comp Sci
Asst Professor Computer Science
