### ISSUE TITLE
Did we lose all of the old code from the blueJ project?

### ISSUE THREAD

**Issue by FriskyJacket** [CCCNJ-CS216/Five-Points#7]
Title

**Comment by natepisarski** [comment]
Nope. Actually, that's one of the reasons were using git. All changes can be rolled back to any specific commit. Or you can go back to a commit and browse the files right on github. Tap "commits" on the repo and click whatever history you want to browse. The zip download when you're browsing old files is then the history at that point

Closes #7

**Comment by FriskyJacket** [comment]
Thanks.
